name: fitbit
channels:
  - defaults
dependencies:
  - pip
  - python-dateutil
  - requests-oauthlib
  - termcolor
  - pip:
      - git+https://github.com/orcasgit/python-fitbit.git
      - git+https://github.com/dtcooper/python-fitparse.git
